;(() => {
  try {
    console.log('ax')
  } catch (err) {
    console.log(err)
  }
})()
